In [27]:
import pandas as pd
customer = pd.read_csv("messy_customers.csv")
order_details = pd.read_csv("messy_order_items.csv")
orders= pd.read_csv("messy_orders.csv")
products= pd.read_csv("messy_products.csv",encoding = "latin1")


df = pd.DataFrame({
    "ID":[101,102,103,104,105,106,107,108,109,110],
    "order_item":["Monitor","Keyboard","Mouse","CPU","GPU","Motherboard","RAM","SSD","UPS","scanner"],
    "price":[1000,2000,3000,4000,5000,6000,7000,8000,9000,45600]
},
                  index=["amit","sumit","rohan","sohan","mohan","manish","priya","shreya","jay","mayank"])

In [3]:
order_details

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

In [6]:
order_details [order_details['unit_price'] > 50000]

      order_item_id order_id product_id  quantity  unit_price
2                 3   O00589       P007       2.0     77415.0
4                 5   O00322       P036       2.0     58380.0
7                 8   O00046       P062       2.0     87380.0
11               12   O01134       P076       3.0     74274.0
17               18   O00913       P065       1.0     55890.0
...             ...      ...        ...       ...         ...
2023            549   O00681       P002       3.0     63663.0
2027            197   O00301       P003       3.0     60818.0
2036           1814   O00575       P080       0.0     80491.0
2037            716   O00473       P040       3.0     55590.0
2049           1233   O00581       P047       1.0     89224.0

[457 rows x 5 columns]

In [9]:
order_details [(order_details['unit_price'] > 50000) & (order_details['quantity']==2.0)]

      order_item_id order_id product_id  quantity  unit_price
2                 3   O00589       P007       2.0     77415.0
4                 5   O00322       P036       2.0     58380.0
7                 8   O00046       P062       2.0     87380.0
24               25   O00586       P010       2.0     60248.0
137             138   O00979       P074       2.0     85963.0
...             ...      ...        ...       ...         ...
1889           1890   O00021       P039       2.0     87975.0
1918           1919   O00871       P075       2.0     72184.0
2005           1420   O00327       P039       2.0     53326.0
2010           1532   O00015       P075       2.0     56095.0
2018           1372   O01191       P076       2.0     89156.0

[67 rows x 5 columns]

In [10]:
order_details [(order_details['unit_price'] > 50000) | (order_details['quantity']==2.0)]

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
7                 8   O00046       P062       2.0     87380.0
...             ...      ...        ...       ...         ...
2036           1814   O00575       P080       0.0     80491.0
2037            716   O00473       P040       3.0     55590.0
2043           1601   O00843       P078       2.0         NaN
2044            999   O00921       P073       2.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[712 rows x 5 columns]

in python and condition is implemented by 'and'
in pandas and condition is implemented by &


in python or condition is implemented by 'or'
in pandas or condition is implemented by |

In [ ]:
order_details.query() # WE can use a syntax like MYSQL

In [12]:
# select * from order_details where quantity=0;
order_details.query("quantity==0")

      order_item_id order_id product_id  quantity  unit_price
6                 7   O00288       P070       0.0         NaN
20               21   O00594       P076       0.0     59441.0
26               27   O00912       P047       0.0         NaN
32               33   O00882       P014       0.0     25382.0
45               46   O01134       P017       0.0         NaN
...             ...      ...        ...       ...         ...
2020            306   O00354       P053       0.0         NaN
2034           1772   O00900       P058       0.0         NaN
2036           1814   O00575       P080       0.0     80491.0
2038           1805   O00977       P058       0.0         NaN
2040           1161   O01195       P020       0.0         NaN

[341 rows x 5 columns]

In [13]:
# select * from order_details where quantity=0 and unit_price>=60000;
order_details.query("quantity==0 and unit_price>=60000")

      order_item_id order_id product_id  quantity  unit_price
115             116   O01012       P064       0.0     87243.0
132             133   O00996       P057       0.0     67021.0
209             210   O00155       P061       0.0     86125.0
212             213   O00615       P022       0.0     74631.0
213             214   O00412       P052       0.0     75650.0
236             237   O00442       P074       0.0     83343.0
253             254   O00053       P040       0.0     65419.0
258             259   O01095       P063       0.0     65624.0
265             266   O00398       P015       0.0     79531.0
273             274   O00384       P080       0.0     63653.0
312             313   O00029       P025       0.0     63996.0
353             354   O00185       P077       0.0     86726.0
378             379   O00324       P035       0.0     60638.0
379             380   O00996       P052       0.0     74550.0
395             396   O00465       P069       0.0     65775.0
410             411   O01054       P072       0.0     85189.0
505             506   O00983       P076       0.0     68653.0
561             562   O00807       P039       0.0     74538.0
629             630   O00650       P052       0.0     83661.0
734             735   O00555       P027       0.0     71451.0
815             816   O00675       P007       0.0     82381.0
825             826   O00136       P078       0.0     86702.0
874             875   O00165       P033       0.0     76814.0
898             899   O00038       P050       0.0     76969.0
951             952   O00838       P041       0.0     84151.0
967             968   O00293       P020       0.0     72487.0
1137           1138   O00523       P059       0.0     79384.0
1200           1201   O00115       P054       0.0     64414.0
1219           1220   O00304       P009       0.0     82068.0
1236           1237   O00817       P052       0.0     63723.0
1260           1261   O00085       P046       0.0     76395.0
1263           1264   O00235       P025       0.0     85365.0
1265           1266   O00075       P071       0.0     77028.0
1292           1293   O00002       P026       0.0     61323.0
1349           1350   O00580       P015       0.0     87369.0
1351           1352   O00720       P018       0.0     87099.0
1352           1353   O01001       P061       0.0     71257.0
1360           1361   O01163       P026       0.0     68997.0
1420           1421   O00508       P022       0.0     86883.0
1477           1478   O00613       P060       0.0     80163.0
1566           1567   O01089       P041       0.0     60933.0
1603           1604   O00409       P075       0.0     78121.0
1679           1680   O00577       P005       0.0     66857.0
1727           1728   O00410       P037       0.0     70501.0
1759           1760   O00309       P068       0.0     68387.0
1760           1761   O01072       P062       0.0     81703.0
1813           1814   O00575       P080       0.0     80491.0
1838           1839   O00889       P044       0.0     61684.0
1862           1863   O00706       P067       0.0     85639.0
1867           1868   O00790       P034       0.0     77081.0
1874           1875   O00772       P012       0.0     73196.0
1895           1896   O00590       P017       0.0     77242.0
1904           1905   O00753       P018       0.0     74253.0
1997           1998   O00703       P008       0.0     76524.0
2006            411   O01054       P072       0.0     85189.0
2012           1261   O00085       P046       0.0     76395.0
2036           1814   O00575       P080       0.0     80491.0

In [14]:
n = 75000
q =0

order_details.query("quantity==@q and unit_price>@n")

      order_item_id order_id product_id  quantity  unit_price
115             116   O01012       P064       0.0     87243.0
209             210   O00155       P061       0.0     86125.0
213             214   O00412       P052       0.0     75650.0
236             237   O00442       P074       0.0     83343.0
265             266   O00398       P015       0.0     79531.0
353             354   O00185       P077       0.0     86726.0
410             411   O01054       P072       0.0     85189.0
629             630   O00650       P052       0.0     83661.0
815             816   O00675       P007       0.0     82381.0
825             826   O00136       P078       0.0     86702.0
874             875   O00165       P033       0.0     76814.0
898             899   O00038       P050       0.0     76969.0
951             952   O00838       P041       0.0     84151.0
1137           1138   O00523       P059       0.0     79384.0
1219           1220   O00304       P009       0.0     82068.0
1260           1261   O00085       P046       0.0     76395.0
1263           1264   O00235       P025       0.0     85365.0
1265           1266   O00075       P071       0.0     77028.0
1349           1350   O00580       P015       0.0     87369.0
1351           1352   O00720       P018       0.0     87099.0
1420           1421   O00508       P022       0.0     86883.0
1477           1478   O00613       P060       0.0     80163.0
1603           1604   O00409       P075       0.0     78121.0
1760           1761   O01072       P062       0.0     81703.0
1813           1814   O00575       P080       0.0     80491.0
1862           1863   O00706       P067       0.0     85639.0
1867           1868   O00790       P034       0.0     77081.0
1895           1896   O00590       P017       0.0     77242.0
1997           1998   O00703       P008       0.0     76524.0
2006            411   O01054       P072       0.0     85189.0
2012           1261   O00085       P046       0.0     76395.0
2036           1814   O00575       P080       0.0     80491.0

In [15]:
order_details.query("100<order_item_id<200") # chained comparision

      order_item_id order_id product_id  quantity  unit_price
100             101   O01101       P080       0.0         NaN
101             102   O01002       P021       0.0     39349.0
102             103   O00871       P039       0.0         NaN
103             104   O00048       P057       NaN         NaN
104             105   O00953       P008       0.0         NaN
...             ...      ...        ...       ...         ...
198             199   O01065       P013       NaN     65979.0
2011            111   O01090       P018       0.0     41057.0
2015            159   O00727       P002       1.0     34931.0
2027            197   O00301       P003       3.0     60818.0
2039            156   O00621       P020       1.0         NaN

[103 rows x 5 columns]

In [17]:
order_details [ order_details.isnull() ]

      order_item_id order_id product_id  quantity  unit_price
0               NaN      NaN        NaN       NaN         NaN
1               NaN      NaN        NaN       NaN         NaN
2               NaN      NaN        NaN       NaN         NaN
3               NaN      NaN        NaN       NaN         NaN
4               NaN      NaN        NaN       NaN         NaN
...             ...      ...        ...       ...         ...
2045            NaN      NaN        NaN       NaN         NaN
2046            NaN      NaN        NaN       NaN         NaN
2047            NaN      NaN        NaN       NaN         NaN
2048            NaN      NaN        NaN       NaN         NaN
2049            NaN      NaN        NaN       NaN         NaN

[2050 rows x 5 columns]

In [19]:
order_details["quantity"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
2045    False
2046    False
2047     True
2048    False
2049    False
Name: quantity, Length: 2050, dtype: bool

In [20]:
order_details[order_details["quantity"].isnull()]

      order_item_id order_id product_id  quantity  unit_price
12               13   O00147       P072       NaN         NaN
13               14   O00103       P040       NaN     27760.0
15               16   O00084       P066       NaN         NaN
18               19   O00648       P022       NaN         NaN
70               71   O00232       P078       NaN     74303.0
...             ...      ...        ...       ...         ...
2026            546   O00636       P010       NaN         NaN
2029            594   O00372       P057       NaN         NaN
2032            650   O00458       P040       NaN     17163.0
2042            997   O01103       P011       NaN     33021.0
2047            399   O00053       P055       NaN         NaN

[318 rows x 5 columns]

In [21]:
# find all the null value inside a table
order_details.isnull().sum()

order_item_id       0
order_id            0
product_id          0
quantity          318
unit_price       1011
dtype: int64

In [23]:
order_details.drop(columns=["unit_price"])

      order_item_id order_id product_id  quantity
0                 1   O00380       P033       2.0
1                 2   O00857       P010       1.0
2                 3   O00589       P007       2.0
3                 4   O00112       P045       2.0
4                 5   O00322       P036       2.0
...             ...      ...        ...       ...
2045           1166   O00667       P034       3.0
2046            841   O00120       P050       4.0
2047            399   O00053       P055       NaN
2048            545   O01182       P005       3.0
2049           1233   O00581       P047       1.0

[2050 rows x 4 columns]

order_details = order_details.drop(columns=["unit_price"])
order_details.drop(columns=["unit_price"],inplace=True)

In [24]:
order_details

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

In [25]:
order_details.drop(columns=["unit_price"],inplace=True)

In [26]:
order_details

      order_item_id order_id product_id  quantity
0                 1   O00380       P033       2.0
1                 2   O00857       P010       1.0
2                 3   O00589       P007       2.0
3                 4   O00112       P045       2.0
4                 5   O00322       P036       2.0
...             ...      ...        ...       ...
2045           1166   O00667       P034       3.0
2046            841   O00120       P050       4.0
2047            399   O00053       P055       NaN
2048            545   O01182       P005       3.0
2049           1233   O00581       P047       1.0

[2050 rows x 4 columns]

In [28]:
order_details

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

In [29]:
order_details.drop(labels=[2049])

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2044            999   O00921       P073       2.0         NaN
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       NaN         NaN
2048            545   O01182       P005       3.0         NaN

[2049 rows x 5 columns]

In [30]:
order_details.dropna()

      order_item_id order_id product_id  quantity  unit_price
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
7                 8   O00046       P062       2.0     87380.0
10               11   O00609       P006       3.0     12037.0
...             ...      ...        ...       ...         ...
2036           1814   O00575       P080       0.0     80491.0
2037            716   O00473       P040       3.0     55590.0
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2049           1233   O00581       P047       1.0     89224.0

[872 rows x 5 columns]

In [31]:
order_details['quantity'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [32]:
order_details.fillna("a")

      order_item_id order_id product_id quantity unit_price
0                 1   O00380       P033      2.0          a
1                 2   O00857       P010      1.0          a
2                 3   O00589       P007      2.0    77415.0
3                 4   O00112       P045      2.0    49066.0
4                 5   O00322       P036      2.0    58380.0
...             ...      ...        ...      ...        ...
2045           1166   O00667       P034      3.0    47907.0
2046            841   O00120       P050      4.0    41680.0
2047            399   O00053       P055        a          a
2048            545   O01182       P005      3.0          a
2049           1233   O00581       P047      1.0    89224.0

[2050 rows x 5 columns]

In [35]:
order_details['quantity'].sum()

np.float64(3449.0)

In [36]:
order_details['quantity'].mean() # 1

np.float64(1.9913394919168592)

In [37]:
order_details['quantity'].median() # 2

np.float64(2.0)

In [38]:
order_details['quantity'].min()

np.float64(0.0)

In [39]:
order_details['quantity'].max()

np.float64(4.0)

In [40]:
round(order_details['quantity'].mean(),0)

np.float64(2.0)

In [42]:
order_details['quantity'].fillna(round(order_details['quantity'].mean(),0),inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9092\937280621.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  order_details['quantity'].fillna(round(order_details['quantity'].mean(),0),inplace=True)

0       2.0
1       1.0
2       2.0
3       2.0
4       2.0
       ...
2045    3.0
2046    4.0
2047    2.0
2048    3.0
2049    1.0
Name: quantity, Length: 2050, dtype: float64

In [43]:
order_details.fillna({'quantity':round(order_details['quantity'].mean(),0)},inplace=True)

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       2.0         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

In [44]:
order_details

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033       2.0         NaN
1                 2   O00857       P010       1.0         NaN
2                 3   O00589       P007       2.0     77415.0
3                 4   O00112       P045       2.0     49066.0
4                 5   O00322       P036       2.0     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034       3.0     47907.0
2046            841   O00120       P050       4.0     41680.0
2047            399   O00053       P055       2.0         NaN
2048            545   O01182       P005       3.0         NaN
2049           1233   O00581       P047       1.0     89224.0

[2050 rows x 5 columns]

In [47]:
order_details['quantity'] = order_details['quantity'].astype(int)

In [48]:
order_details

      order_item_id order_id product_id  quantity  unit_price
0                 1   O00380       P033         2         NaN
1                 2   O00857       P010         1         NaN
2                 3   O00589       P007         2     77415.0
3                 4   O00112       P045         2     49066.0
4                 5   O00322       P036         2     58380.0
...             ...      ...        ...       ...         ...
2045           1166   O00667       P034         3     47907.0
2046            841   O00120       P050         4     41680.0
2047            399   O00053       P055         2         NaN
2048            545   O01182       P005         3         NaN
2049           1233   O00581       P047         1     89224.0

[2050 rows x 5 columns]

In [49]:
order_details [order_details['quantity'] == 0]

      order_item_id order_id product_id  quantity  unit_price
6                 7   O00288       P070         0         NaN
20               21   O00594       P076         0     59441.0
26               27   O00912       P047         0         NaN
32               33   O00882       P014         0     25382.0
45               46   O01134       P017         0         NaN
...             ...      ...        ...       ...         ...
2020            306   O00354       P053         0         NaN
2034           1772   O00900       P058         0         NaN
2036           1814   O00575       P080         0     80491.0
2038           1805   O00977       P058         0         NaN
2040           1161   O01195       P020         0         NaN

[341 rows x 5 columns]

In [50]:
order_details['quantity'].replace({0:1})

0       2
1       1
2       2
3       2
4       2
       ..
2045    3
2046    4
2047    2
2048    3
2049    1
Name: quantity, Length: 2050, dtype: int64

In [51]:
order_details['quantity'] = order_details['quantity'].replace({0:1})

In [52]:
order_details[order_details['quantity']==0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [54]:
order_details['quantity'].value_counts()

quantity
1    711
2    640
3    361
4    338
Name: count, dtype: int64

In [55]:
products

   product_id    product_name     category  base_price
0        P001  Lenovo IdeaPad       Tablet     28151.0
1        P002     Samsung Tab   Smartphone     68660.0
2        P003     HP Pavilion  Accessories         NaN
3        P004      Lenovo Tab       tablet         NaN
4        P005         OnePlus       Tablet         NaN
..        ...             ...          ...         ...
85       P022     Samsung Tab    Accessory         NaN
86       P052    Xiaomi Redmi  smart phone         NaN
87       P010       iPhone 13  smart phone         NaN
88       P059         OnePlus  Accessories         NaN
89       P033  Wireless Mouse       laptop     47453.0

[90 rows x 4 columns]

In [56]:
products.isnull().sum()

product_id       0
product_name     0
category         0
base_price      57
dtype: int64

In [57]:
print(products.to_string())

   product_id    product_name     category  base_price
0        P001  Lenovo IdeaPad       Tablet     28151.0
1        P002     Samsung Tab   Smartphone     68660.0
2        P003     HP Pavilion  Accessories         NaN
3        P004      Lenovo Tab       tablet         NaN
4        P005         OnePlus       Tablet         NaN
5        P006      Laptop Bag       tablet         NaN
6        P007     HP Pavilion  Accessories         NaN
7        P008     HP Pavilion    Accessory         NaN
8        P009       iPhone 13       Tablet     70582.0
9        P010       iPhone 13  smart phone         NaN
10       P011  Lenovo IdeaPad  Accessories         NaN
11       P012  Lenovo IdeaPad    Accessory     27157.0
12       P013  Samsung Galaxy  smart phone     51735.0
13       P014    Xiaomi Redmi       Laptop      5475.0
14       P015      Laptop Bag  smart phone     76755.0
15       P016        iPad Air  smart phone         NaN
16       P017        Keyboard   Smartphone         NaN
17       P018   Dell Inspiron       laptop         NaN
18       P019  Samsung Galaxy   Smartphone         NaN
19       P020   Dell Inspiron   Smartphone         NaN
20       P021      Laptop Bag       laptop         NaN
21       P022     Samsung Tab    Accessory         NaN
22       P023      Lenovo Tab       Tablet         NaN
23       P024     MacBook Air  smart phone         NaN
24       P025   Dell Inspiron       laptop     84776.0
25       P026    Xiaomi Redmi       laptop         NaN
26       P027        iPad Air  smart phone     40595.0
27       P028  Samsung Galaxy       Tablet         NaN
28       P029  Samsung Galaxy  Accessories         NaN
29       P030      Laptop Bag    Accessory     44051.0
30       P031     Samsung Tab  Accessories         NaN
31       P032        iPad Air       Tablet      6095.0
32       P033  Wireless Mouse       laptop     47453.0
33       P034      Laptop Bag       Laptop         NaN
34       P035      Laptop Bag       laptop     77306.0
35       P036  Lenovo IdeaPad       Tablet         NaN
36       P037       iPhone 13       Laptop      2571.0
37       P038    Xiaomi Redmi       laptop         NaN
38       P039    Xiaomi Redmi    Accessory     69520.0
39       P040        Keyboard   Smartphone         NaN
40       P041      Laptop Bag  smart phone         NaN
41       P042     HP Pavilion       laptop         NaN
42       P043         USB Hub    Accessory         NaN
43       P044         OnePlus       Tablet     13294.0
44       P045      Lenovo Tab       Laptop         NaN
45       P046       iPhone 13  Accessories         NaN
46       P047         OnePlus  smart phone         NaN
47       P048  Wireless Mouse       Laptop     47676.0
48       P049  Wireless Mouse   Smartphone     61022.0
49       P050  Lenovo IdeaPad       tablet     59514.0
50       P051        Keyboard  smart phone     18522.0
51       P052    Xiaomi Redmi  smart phone         NaN
52       P053       iPhone 13  Accessories         NaN
53       P054      Laptop Bag   Smartphone     34450.0
54       P055        Keyboard    Accessory         NaN
55       P056  Samsung Galaxy  smart phone         NaN
56       P057  Lenovo IdeaPad       laptop     27615.0
57       P058  Lenovo IdeaPad   Smartphone     41597.0
58       P059         OnePlus  Accessories         NaN
59       P060         USB Hub       laptop         NaN
60       P061      Lenovo Tab       Tablet         NaN
61       P062   Dell Inspiron       Tablet         NaN
62       P063  Wireless Mouse  Accessories         NaN
63       P064  Lenovo IdeaPad  Accessories     81129.0
64       P065   Dell Inspiron  smart phone     58364.0
65       P066     Samsung Tab  smart phone         NaN
66       P067         USB Hub   Smartphone         NaN
67       P068    Xiaomi Redmi       Tablet     43027.0
68       P069         USB Hub       laptop         NaN
69       P070        iPad Air       Tablet         NaN
70       P071       iPhone 13       Tablet     65274.0
71       P072   Dell Inspiron       Tablet         NaN
72       P073      Lenovo Tab    Accessory      3393.0
73       P074     Samsung Tab       tablet         NaN
74       P075       iPhone 13  smart phone         NaN
75       P076  Wireless Mouse    Accessory     15249.0
76       P077  Wireless Mouse  smart phone         NaN
77       P078         USB Hub    Accessory     70378.0
78       P079         OnePlus       tablet         NaN
79       P080         OnePlus       laptop     82478.0
80       P076  Wireless Mouse    Accessory     15249.0
81       P062   Dell Inspiron       Tablet         NaN
82       P072   Dell Inspiron       Tablet         NaN
83       P017        Keyboard   Smartphone         NaN
84       P020   Dell Inspiron   Smartphone         NaN
85       P022     Samsung Tab    Accessory         NaN
86       P052    Xiaomi Redmi  smart phone         NaN
87       P010       iPhone 13  smart phone         NaN
88       P059         OnePlus  Accessories         NaN
89       P033  Wireless Mouse       laptop     47453.0

In [58]:
products["category"].value_counts()

category
smart phone    17
Tablet         16
laptop         13
Accessory      12
Smartphone     11
Accessories    11
tablet          5
Laptop          5
Name: count, dtype: int64

In [60]:
products["category"] = products["category"].str.capitalize()

In [61]:
products["category"].value_counts()

category
Tablet         21
Laptop         18
Smart phone    17
Accessory      12
Smartphone     11
Accessories    11
Name: count, dtype: int64

In [62]:
products["category"].replace({"Accessory":"Accessories" ,"Smart phone" : "Smartphone" })

0          Tablet
1      Smartphone
2     Accessories
3          Tablet
4          Tablet
         ...
85    Accessories
86     Smartphone
87     Smartphone
88    Accessories
89         Laptop
Name: category, Length: 90, dtype: str

In [63]:
products["category"] = products["category"].replace({"Accessory":"Accessories" ,"Smart phone" : "Smartphone" })

In [64]:
products["category"].value_counts()

category
Smartphone     28
Accessories    23
Tablet         21
Laptop         18
Name: count, dtype: int64